version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
      - admin
    networks:
      bridge:
        ipv4_address: 172.20.0.3
    command: ["/bin/bash","./wait.sh"]

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: android@123
      MYSQL_DATABASE: app_db
    ports:
      - "3308:3306"
    networks:
      bridge:
        ipv4_address: 172.20.0.2

  admin:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      bridge:
        ipv4_address: 172.20.0.4

networks:
  bridge:
    ipam:
      config:
        - subnet: 172.20.0.0/16
